### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Snipa3lite** [cadburry6969/qb-cooldown#1]
Is there anyway to get more documentation on this? I want to implement this across store robbery and jewelry robbery, etc

**Comment by cadburry6969** [comment]
I can provide an example but rest on the people how to use it

**Comment by Snipa3lite** [comment]
I'm not sure if I'm daft but I want all my robberies on a global coolsown
together

**Comment by cadburry6969** [comment]
Updated ReadMe "How to use it" 
https://github.com/cadburry6969/qb-cooldown/blob/main/README.md
