### ISSUE TITLE
Error pops up in console 

### ISSUE THREAD

**Issue by Brave-developments** [cadburry6969/qb-cooldown#3]
[  script:qb-cooldown] Error loading script server.lua in resource qb-cooldown: @qb-cooldown/server.lua:19: attempt to index a nil value (global 'QBCore')
[  script:qb-cooldown] stack traceback:
[  script:qb-cooldown] 	@qb-cooldown/server.lua:19: in main chunk
[    c-scripting-core] Failed to load script server.lua.

Maybe i didnt undertsand the step Export method

**Comment by cadburry6969** [comment]
Try latest version
